# Generated by Django 5.0 on 2023-12-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_shoes_remove_product_category_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eCommerce.product')),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=10)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
            ],
            bases=('eCommerce.product',),
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eCommerce.product')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=50)),
            ],
            bases=('eCommerce.product',),
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eCommerce.product')),
                ('breed', models.CharField(max_length=250)),
                ('weight', models.IntegerField(default=0)),
                ('quality', models.CharField(max_length=50)),
            ],
            bases=('eCommerce.product',),
        ),
        migrations.CreateModel(
            name='Skincare',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eCommerce.product')),
                ('brand', models.CharField(max_length=250)),
                ('skincare_type', models.CharField(max_length=50)),
                ('skintype', models.CharField(max_length=50)),
            ],
            bases=('eCommerce.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='model',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='brand',
            field=models.CharField(max_length=250),
        ),
    ]
