# Generated by Django 5.0 on 2023-12-23 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_clothes_gadget_poultry_skincare_product_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'clothes'},
        ),
        migrations.AlterModelOptions(
            name='poultry',
            options={'verbose_name_plural': 'poultries'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name_plural': 'shoes'},
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
